### ISSUE TITLE
Bad casing on roles pages

### ISSUE THREAD

**Issue by anyasomerville** [ukparliament/parliament.uk-lists#172]
Bad casing on certain person roles pages (e.g. [Jeremy Hunt](https://web.archive.org/web/20180719164549/https://beta.parliament.uk/people/x6FOPcns/associations) and [Adam Afriyie](https://web.archive.org/web/20180719164745/https://beta.parliament.uk/people/LOTLFbzi/associations)).
The text should be "MP for".

![image](https://user-images.githubusercontent.com/25383818/42957582-07adc346-8b7b-11e8-9293-bda83ae37eb3.png)

**Comment by langsamu** [comment]
![image](https://user-images.githubusercontent.com/240741/42958070-7079b776-8b7c-11e8-90ab-df05e55ff74f.png)
